# TinyGo Makefile
# Generated by TinyGo Toolkit

TARGET ?= pico2
PORT ?= /dev/ttyACM0
MAIN ?= cmd/main.go
BUILD_DIR ?= build

.PHONY: build flash clean monitor size

build:
	tinygo build -target=$(TARGET) -o $(BUILD_DIR)/firmware $(MAIN)

flash:
	tinygo flash -target=$(TARGET) -port=$(PORT) $(MAIN)

clean:
	rm -rf $(BUILD_DIR)

monitor:
	@echo "Connecting to $(PORT) at 115200 baud..."
	@stty -F $(PORT) 115200 raw -echo
	@cat $(PORT)

size:
	tinygo build -target=$(TARGET) -size=full -o /dev/null $(MAIN)
